#!/usr/bin/env sh

. "$(dirname -- "$0")/_/husky.sh"

echo "=========================\n"
echo "Running pre-commit hook \n"

echo "=========================\n"
echo "Running test \n"
mvn clean test

if [ $? -ne 0 ]; then
 echo "Tests must pass before commit!\n"
 exit 1
fi

echo "=========================\n"
echo "Running code style validation \n"
mvn validate

if [ $? -ne 0 ]; then
 echo "Code style validation warning\n"
 exit 1
fi


